---
types_of_change:
  - New feature/s
  - Improvement of existing feature/s
  - Bugfix
  - Dev/Test/CI Stuff
  - Devdocs
  - Other

active_release_name: Icecream
changelog_subdirectory_for_new_entries: 1-fs-release-icecream