nelmio_api_doc:
  documentation:
    info:
      title: Foodsharing API
      description: https://devdocs.foodsharing.de
      version: 1.0.0

  areas:
    path_patterns:
      - ^/api(?!/swagger.json$)
