when@prod:
when@dev:
  framework:
    rate_limiter:
      login:
        policy: 'token_bucket'
        limit: 30
        rate: { interval: '1 second', amount: 1 }

when@test:
  framework:
    rate_limiter:
      login:
        policy: 'no_limit'
        limit: 0
