version: '2'
services:

  # nginx
  #------------------------------------

  # proxies connections to app/chat

  web:
    build: ./docker-images/web
    ports:
      - 8080:8080
    depends_on:
      - app
      - chat
    volumes:
      - ./:/app

  # main php app
  #------------------------------------

  app:
    build: ./docker-images/app
    ports:
      - 9000:9000
    links:
      - redis:redis
      - db:db
      - chat:chat
    volumes:
      - ./:/app

  # nodejs socket.io server
  #------------------------------------

  chat:
    build: ./docker-images/chat
    ports:
      - 1337:1337
      - 1338:1338
    volumes:
      - ./:/app

  # mysql
  #------------------------------------

  db:
    image: orchardup/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodsharing

  # redis
  #------------------------------------

  redis:
    image: redis
    ports:
      - 6379:6379
