index:
  path: /
  controller: Foodsharing\Entrypoint\IndexController

xhr:
  path: /xhr.php
  controller: Foodsharing\Entrypoint\XhrController

xhrapp:
  path: /xhrapp.php
  controller: Foodsharing\Entrypoint\XhrAppController