messages:
  type: annotation
  prefix: /api
  resource: ../..//src/Controller/
  defaults: {_format: json}

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
  prefix:   /api/doc

index:
  path: /
  controller: Foodsharing\Entrypoint\IndexController

xhr:
  path: /xhr.php
  controller: Foodsharing\Entrypoint\XhrController

xhrapp:
  path: /xhrapp.php
  controller: Foodsharing\Entrypoint\XhrAppController