messages:
  type: rest
  prefix: /api
  resource: ../src/Controller
  defaults: {_format: json}

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
  prefix:   /api/doc