version: '2'
services:

  # nginx
  #------------------------------------

  # proxies connections to app/chat

  web:
    container_name: foodsharing_test_web
    image: registry.gitlab.com/foodsharing-dev/images/web:1.0
    ports:
      - 28080:8080
    expose:
      - 8080
    depends_on:
      - app
      - chat
    volumes:
      - ../:/app

  # main php app
  #------------------------------------

  app:
    container_name: foodsharing_test_app
    image: registry.gitlab.com/foodsharing-dev/images/php:2.1
    working_dir: /app
    expose:
      - 9000
    links:
      - redis:redis
      - db:db
      - chat:chat
    volumes:
      - ../:/app
      - selenium_downloads:/downloads
    environment:
      FS_ENV: test
      REDIS_HOST: redis

  # php mail queue runner
  #------------------------------------

  mailqueuerunner:
    container_name: foodsharing_test_mailqueuerunner
    image: registry.gitlab.com/foodsharing-dev/images/php:2.1
    command: php run.php mails index
    working_dir: /app
    links:
      - maildev
      - redis:redis
      - db:db
    volumes:
      - ../:/app
    environment:
      FS_ENV: dev

  chat:
    container_name: foodsharing_test_chat
    image: registry.gitlab.com/foodsharing-dev/images/chat:1.1
    command: sh -c "yarn && node server.js 0.0.0.0"
    working_dir: /app/chat
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    expose:
      - 1337
      - 1338
    volumes:
      - ../:/app

  # mysql
  #------------------------------------

  db:
    container_name: foodsharing_test_db
    image: registry.gitlab.com/foodsharing-dev/images/db/test:1.0
    # so we can mount tmpfs inside container
    privileged: true
    expose:
      - 3306
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../:/app

  # redis
  #------------------------------------

  redis:
    container_name: foodsharing_test_redis
    image: redis:alpine
    expose:
      - 6379

  # selenium
  #------------------------------------

  # for running browser-based tests

  selenium:
    container_name: foodsharing_test_selenium
    image: registry.gitlab.com/foodsharing-dev/images/selenium:1.0
    shm_size: 256M
    links:
      - web:web
    expose:
      - 4444
    volumes:
      - selenium_downloads:/home/seluser/Downloads

  # phpmyadmin
  #------------------------------------

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: foodsharing_test_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 28081:80
    volumes:
      - /sessions

  # maildev
  #------------------------------------

  maildev:
    command: >
      bin/maildev
        --web 80
        --smtp 25
        --hide-extensions STARTTLS
    image: djfarrelly/maildev
    container_name: foodsharing_test_maildev
    ports:
      - 28083:80


volumes:
  selenium_downloads:
