# expose, ports are additive, means each environment requires a own port mapping instead of a global one.
# Prebuild custom images are located at gitlab.com/foodsharing-dev/images/

version: '2'
services:
  # nginx
  #------------------------------------
  nginx:
    container_name: foodsharing_nginx
    image: registry.gitlab.com/foodsharing-dev/images/nginx:26
    # build: ./build/nginx
    depends_on:
      - app
      - frontend
      - websocket
    volumes:
      - ../:/app:delegated
    expose:
      - 8080
    # ports:
    #   - 80:8080

  # Customized PHP
  #------------------------------------
  app:
    user: ${CURRENT_USER}
    container_name: foodsharing_backend
    image: registry.gitlab.com/foodsharing-dev/images/php:26
    working_dir: /app
    depends_on:
      - db
      - redis
      - mailqueuerunner
      - influxdb
      - websocket
    volumes:
      - ../:/app:delegated
      - ./conf/php/dev-config.${FS_PLATFORM}.ini:/usr/local/etc/php/conf.d/dev-config.ini:cached
    # environment:
    #   - FS_ENV=dev
    expose:
      - 9000
    # ports:
    #   - 9000:9000

  # Frontend
  #------------------------------------
  frontend:
    user: ${CURRENT_USER}
    container_name: foodsharing_frontend
    image: registry.gitlab.com/foodsharing-dev/images/node:26
    # command: sh -c "yarn && yarn dev"
    command: sh -c "yarn && yarn build"
    working_dir: /app/frontend
    volumes:
      - ../:/app:delegated
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      # - NPM_CONFIG_CACHE=/tmp/.npm-cache
    expose:
      - 3000
      - 24678
    # ports:
    #   - 8080:3000
    #   - "24678:24678"

  # PHP mail queue runner
  #------------------------------------
  mailqueuerunner:
    user: ${CURRENT_USER}
    container_name: foodsharing_mailqueuerunner
    image: registry.gitlab.com/foodsharing-dev/images/php:26
    command: php run.php Mails queueWorker
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - maildev
    working_dir: /app
    volumes:
      - ../:/app:delegated
    # environment:
    #   - FS_ENV=dev

  # Socket.io server
  #------------------------------------
  websocket:
    user: ${CURRENT_USER}
    container_name: foodsharing_websocket
    image: registry.gitlab.com/foodsharing-dev/images/node:26
    working_dir: /app/websocket
    command: sh -c "yarn && yarn ts-node-dev src/index.ts 0.0.0.0"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ../:/app:delegated
    expose:
      - 1337
      - 1338
    # ports:
    #   - 1337:1337
    #   - 1338:1338

  # mysql
  #------------------------------------
  db:
    container_name: foodsharing_db
    image: registry.gitlab.com/foodsharing-dev/images/mariadb:26
    environment:
      # - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Berlin
    volumes:
      - database:/var/lib/mysql-tmpfs # based on the image configuration
    expose:
      - 3306
    # ports:
    #   - 3306:3306

  # redis
  #------------------------------------
  redis:
    container_name: foodsharing_redis
    image: registry.gitlab.com/foodsharing-dev/images/redis:26
    expose:
      - 6379
    # ports:
    #   - 6379:6379

  # phpmyadmin
  #------------------------------------
  phpmyadmin:
    container_name: foodsharing_phpmyadmin
    image: registry.gitlab.com/foodsharing-dev/images/phpmyadmin:26
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: unless-stopped
    expose:
      - 80
    # ports:
    #   - 8081:80

  # maildev
  #------------------------------------
  maildev:
    container_name: foodsharing_maildev
    image: registry.gitlab.com/foodsharing-dev/images/maildev:26
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
      # - MAILDEV_HIDE_EXTENSIONS=STARTTLS
    expose:
      - 1080
      - 1025
    # ports:
    #   - 8084:80

  # influxdb
  # used for mail sending tracking and server monitoring
  #------------------------------------
  influxdb:
    container_name: foodsharing_influxdb
    image: registry.gitlab.com/foodsharing-dev/images/influxdb:26
    command: >
      influxd -config /etc/influxdb/influxdb.toml
    environment:
      - INFLUXDB_ADMIN_ENABLED=false
      - INFLUXDB_DB=foodsharing
    volumes:
      - influxdb:/var/lib/influxdb:cached
      - ./conf/influxdb/influxdb.toml:/etc/influxdb/influxdb.toml:cached
    expose:
      - 8083
      - 8089/udp
      - 8086
    # ports:
    #   - 8083:8083
    #   - 8089:8089/udp
    #   - 8086:8086

  # # docs
  # # A plattform for the developer documentations
  # #------------------------------------
  # docs:
  #   user: ${CURRENT_USER}
  #   container_name: foodsharing_docs
  #   image: registry.gitlab.com/foodsharing-dev/images/docs:26
  #   working_dir: /app/docs
  #   volumes:
  #     - ../:/app:delegated
  #   expose:
  #     - 3000
  #   # ports:
  #   #   - 3000:3000

volumes:
  database:
  influxdb:
