# expose, ports are additive, means each environment requires a own port mapping instead of a global one.

version: '2'
services:
  # nginx
  #------------------------------------
  nginx:
    container_name: foodsharing_test_nginx
    ports:
      - 28080:8080

  # Customized PHP
  #------------------------------------
  app:
    container_name: foodsharing_test_app
    environment:
      FS_ENV: test
    ports:
      - 29000:9000

  # Webpack client
  #------------------------------------
  client:
    container_name: foodsharing_test_client
    command: sh -c "yarn && yarn dev"
    ports:
      - 28090:8080

  # PHP mail queue runner
  #------------------------------------
  mailqueuerunner:
    container_name: foodsharing_test_mailqueuerunner
    environment:
      FS_ENV: test

  # Socket.io server
  #------------------------------------
  websocket:
    container_name: foodsharing_test_websocket
    ports:
      - 21337:1337
      - 21338:1338

  # mysql
  #------------------------------------
  db:
    container_name: foodsharing_test_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 23306:3306

  # redis
  #------------------------------------
  redis:
    container_name: foodsharing_test_redis
    ports:
      - 36379:6379

  # phpmyadmin
  #------------------------------------
  phpmyadmin:
    container_name: foodsharing_test_phpmyadmin
    ports:
      - 28081:80

  # maildev
  #------------------------------------
  maildev:
    container_name: foodsharing_test_maildev
    ports:
      - 28084:80

  # influxdb
  # used for mail sending tracking and server monitoring
  #------------------------------------
  influxdb:
    container_name: foodsharing_test_influxdb
    ports:
      - 28083:8083
      - 28089:8089/udp
      - 28086:8086

  # mdbook
  # A plattform for the developer documentations
  #------------------------------------
  docs:
    container_name: foodsharing_test_docs
    ports:
      - 26000:3000
      - 26002:3001

  # selenium
  # for running browser-based tests
  #------------------------------------
  selenium:
    user: ${CURRENT_USER}
    container_name: foodsharing_test_selenium
    image: selenium/standalone-chrome:3.141.59-20200409
    shm_size: 2gb
    depends_on:
      - nginx
    volumes:
      - selenium_downloads:/home/seluser/Downloads:cached

volumes:
  selenium_downloads:
