version: '3'
services:

  web:
    ports:
      - "18080:8080"

  app:
    volumes:
      - ${PWD}/docker/conf/app/php.dev.ini:/usr/local/etc/php/conf.d/dev-config.ini

  client:
    ports:
      - "8080:8080"
      - "8081:8081"

  chat:
    ports:
      - "11337:1337"
      - "11338:1338"

  db:
    ports:
      - "13306:3306"

  redis:
    ports:
      - "16379:6379"

  phpmyadmin:
    ports:
      - "18081:80"

  maildev:
    ports:
      - "18084:80"
