# expose, ports are additive, means each environment requires a own port mapping instead of a global one.

version: '2'
services:
  # nginx
  #------------------------------------
  nginx:
    container_name: foodsharing_ci_nginx
    ports:
      - 38080:8080

  # Customized PHP
  #------------------------------------
  app:
    container_name: foodsharing_ci_app
    environment:
      FS_ENV: test
    ports:
      - 39000:9000

  # Webpack client
  #------------------------------------
  client:
    container_name: foodsharing_ci_client
    command: sh -c "yarn && yarn build"
    ports:
      - 38090:8080

  # PHP mail queue runner
  #------------------------------------
  mailqueuerunner:
    container_name: foodsharing_ci_mailqueuerunner
    environment:
      FS_ENV: test

  # Socket.io server
  #------------------------------------
  websocket:
    container_name: foodsharing_ci_websocket
    ports:
      - 31337:1337
      - 31338:1338

  # mysql
  #------------------------------------
  db:
    container_name: foodsharing_ci_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33306:3306

  # redis
  #------------------------------------
  redis:
    container_name: foodsharing_ci_redis
    ports:
      - 36379:6379

  # phpmyadmin
  #------------------------------------
  phpmyadmin:
    container_name: foodsharing_ci_phpmyadmin
    ports:
      - 38081:80

  # maildev
  #------------------------------------
  maildev:
    container_name: foodsharing_ci_maildev
    ports:
      - 38084:80

  # influxdb
  # used for mail sending tracking and server monitoring
  #------------------------------------
  influxdb:
    container_name: foodsharing_ci_influxdb
    ports:
      - 38083:8083
      - 38089:8089/udp
      - 38086:8086

  # mdbook
  # A plattform for the developer documentations
  #------------------------------------
  docs:
    container_name: foodsharing_ci_docs
    ports:
      - 33000:3000
      - 33001:3001

  # selenium
  # for running browser-based cis
  #------------------------------------
  selenium:
    user: ${CURRENT_USER}
    container_name: foodsharing_ci_selenium
    image: selenium/standalone-chrome
    shm_size: 512M
    depends_on:
      - nginx
    volumes:
      - selenium_downloads:/home/seluser/Downloads:cached

  # php container for running codeception
  #------------------------------------
  codeception:
    container_name: foodsharing_ci_codeception
    build: ./build/php-ci
    depends_on:
      - db
      - redis
      - mailqueuerunner
      - websocket
      - influxdb
    environment:
      FS_ENV: test
    volumes:
      - selenium_downloads:/downloads
      - vendor_cache:/app/vendor
      - /dev/null:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

volumes:
  selenium_downloads:
  vendor_cache:
