version: '3'
services:

  web:
    image: "foodsharing_${FS_ENV}_web_build"
    build:
      context: ..
      dockerfile: docker/ci/web/Dockerfile
    ports:
      - "38080:8080"

  app:
    image: "foodsharing_${FS_ENV}_app_build"
    build:
      context: ..
      dockerfile: docker/ci/php/Dockerfile
    volumes:
      - selenium_downloads:/downloads
      - php_vendor:/app/vendor
      - /dev/null:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  mailqueuerunner:
    volumes:
      - selenium_downloads:/downloads
      - php_vendor:/app/vendor

  chat:
    image: "foodsharing_${FS_ENV}_chat_build"
    build:
      context: ../chat
      dockerfile: ci/chat/Dockerfile

  db:
    image: "foodsharing_${FS_ENV}_db_build"
    build:
      context: ..
      dockerfile: docker/ci/db/Dockerfile
    ports:
      - "33306:3306"

  # selenium
  #------------------------------------

  # for running browser-based tests

  selenium:
    container_name: "foodsharing_${FS_ENV}_selenium"
    image: registry.gitlab.com/foodsharing-dev/images/selenium:1.2
    shm_size: 256M
    links:
      - web:web
    expose:
      - 4444
    volumes:
      - selenium_downloads:/home/seluser/Downloads

volumes:
  selenium_downloads:
  php_vendor:
