version: '3'
services:

  web:
    ports:
      - "28080:8080"

  app:
    volumes:
      - selenium_downloads:/downloads
      - /dev/null:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  db:
    ports:
      - "23306:3306"

  phpmyadmin:
    ports:
      - "28081:80"

  maildev:
    ports:
      - "28083:80"

  # selenium
  #------------------------------------

  # for running browser-based tests

  selenium:
    container_name: foodsharing_test_selenium
    image: registry.gitlab.com/foodsharing-dev/images/selenium:1.2
    shm_size: 256M
    links:
      - web:web
    expose:
      - 4444
    volumes:
      - selenium_downloads:/home/seluser/Downloads

volumes:
  selenium_downloads:
