index:
  path: /
  controller: Foodsharing\Entrypoint\IndexController

website:
  type: annotation
  prefix: /
  resource: ../src/Modules/

xhr:
  path: /xhr
  controller: Foodsharing\Entrypoint\XhrController

xhrapp:
  path: /xhrapp
  controller: Foodsharing\Entrypoint\XhrAppController

mock:
  type: annotation
  prefix: /mock
  resource: ../src/Mock/
  condition: "'%kernel.environment%' in ['dev', 'test']"