#!/bin/bash
# run docker-compose with the container specified by $FS_ENV and a suitable project name
# which command to run by docker-compose and additional arguments is specified by the arguments
# of this script

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./inc.sh
source "$dir"/inc.sh

if ! [ -x "$(command -v docker-compose)" ]; then
  dcCmd=podman-compose
else
  dcCmd=docker-compose
fi

$dcCmd \
  --file "$dir"/../docker/docker-compose."$FS_ENV".yml \
  --project-name foodsharing_"$FS_ENV" \
  "$@"
