#!/bin/bash

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./inc.sh
source "$dir"/inc.sh

echo "Stopping containers"
if ! [ -x "$(command -v docker-compose)" ]; then
  dc down
else
  dc stop
fi

echo "All stopped!"
